ignoreWorkspaceRootCheck: true
lockfileIncludeTarballUrl: true
linkWorkspacePackages: true
preferWorkspacePackages: true
enableGlobalVirtualStore: false
packages:
  - .
  - bundler
onlyBuiltDependencies:
  - electron
  - esbuild
overrides:
  'eslint>espree': '^10.4.0'
  '@eslint/eslintrc>espree': '^10.4.0'
